# Generated by Django 2.2.1 on 2020-01-05 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jeep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miledge", models.PositiveIntegerField()),
                ("task", models.CharField(max_length=128)),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(2020, 1, 5, 19, 44, 51, 865680)
                    ),
                ),
                ("mechanic", models.CharField(default="Miłosz", max_length=32)),
                (
                    "parts_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "labor_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("done", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shooting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pistol", "Pistolet"),
                            ("rifle", "Karabin"),
                            ("gun", "Strzelba"),
                        ],
                        max_length=16,
                    ),
                ),
                ("year", models.PositiveIntegerField(default=2020)),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(2020, 1, 5, 19, 44, 51, 866270)
                    ),
                ),
                ("place", models.CharField(max_length=128)),
                ("competition", models.CharField(max_length=32)),
                ("score", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "confirmation",
                    models.FileField(blank=True, null=True, upload_to="shooting/%Y"),
                ),
                ("done", models.BooleanField(default=True)),
            ],
        ),
    ]
