# Generated by Django 2.2.1 on 2020-03-08 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hobby", "0012_auto_20200307_1800")]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="jeep",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2020, 3, 8, 19, 55, 41, 925791)
            ),
        ),
        migrations.AlterField(
            model_name="shooting",
            name="category",
            field=models.CharField(
                choices=[
                    ("pistol", "Pistolet"),
                    ("rifle", "Karabin"),
                    ("gun", "Strzelba"),
                    ("docs", "Dokumenty"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="shooting",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2020, 3, 8, 19, 55, 41, 926360)
            ),
        ),
    ]
