# Generated by Django 2.2.1 on 2020-03-12 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0013_auto_20200308_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='jeep',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 12, 19, 56, 55, 295126)),
        ),
        migrations.AlterField(
            model_name='shooting',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 12, 19, 56, 55, 296176)),
        ),
    ]
