# Generated by Django 2.2.4 on 2020-06-05 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hobby", "0015_auto_20200404_2040")]

    operations = [
        migrations.AlterField(
            model_name="jeep",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2020, 6, 5, 17, 4, 2, 666032)
            ),
        ),
        migrations.AlterField(
            model_name="shooting",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2020, 6, 5, 17, 4, 2, 666734)
            ),
        ),
    ]
