# Generated by Django 2.2.4 on 2020-06-14 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hobby", "0016_auto_20200605_1704")]

    operations = [
        migrations.AlterField(
            model_name="jeep",
            name="date",
            field=models.DateField(default=datetime.date(2020, 6, 14)),
        ),
        migrations.AlterField(
            model_name="shooting",
            name="date",
            field=models.DateField(default=datetime.date(2020, 6, 14)),
        ),
    ]
