# Generated by Django 2.2.4 on 2020-07-01 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hobby", "0017_auto_20200614_1924")]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="note",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="jeep",
            name="date",
            field=models.DateField(default=datetime.date(2020, 7, 1)),
        ),
        migrations.AlterField(
            model_name="quote",
            name="text",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="shooting",
            name="date",
            field=models.DateField(default=datetime.date(2020, 7, 1)),
        ),
    ]
