# Generated by Django 2.2.1 on 2020-01-07 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimeTracker",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("task", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("time_effort", models.DecimalField(decimal_places=2, max_digits=4)),
                ("paid", models.BooleanField()),
                ("workday", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimeSummary",
            fields=[],
            options={
                "verbose_name": "Time Summary",
                "verbose_name_plural": "Times Summary",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("hepterakt.timetracker",),
        ),
    ]
