# Generated by Django 2.2.1 on 2020-01-07 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hepterakt', '0002_auto_20200107_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracker',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='workday',
            field=models.DateField(default=datetime.datetime(2020, 1, 7, 14, 44, 33, 117490)),
        ),
    ]
