# Generated by Django 2.2.1 on 2020-01-10 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hepterakt", "0005_auto_20200110_1915"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="contact_ind",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="timetracker",
            name="workday",
            field=models.DateField(
                default=datetime.datetime(2020, 1, 10, 19, 39, 21, 30008)
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="application_date",
            field=models.DateField(
                default=datetime.datetime(2020, 1, 10, 19, 39, 21, 30957)
            ),
        ),
    ]
