# Generated by Django 2.2.4 on 2020-06-14 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("hepterakt", "0014_auto_20200605_1704")]

    operations = [
        migrations.AlterField(
            model_name="timetracker",
            name="workday",
            field=models.DateField(
                default=datetime.datetime(2020, 6, 14, 19, 24, 1, 953500, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="application_date",
            field=models.DateField(
                default=datetime.datetime(2020, 6, 14, 19, 24, 1, 954281, tzinfo=utc)
            ),
        ),
    ]
