# Generated by Django 2.2.4 on 2020-06-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("things", "0002_thing_bought")]

    operations = [
        migrations.CreateModel(
            name="Warranty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thing", models.CharField(max_length=128)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("receipt", models.FileField(upload_to="")),
            ],
        )
    ]
