# Generated by Django 2.2.1 on 2020-01-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "very bad"),
                            (2, "bad"),
                            (3, "so so"),
                            (4, "good"),
                            (5, "very good"),
                        ],
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("tod_do", "To do"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                        ],
                        max_length=16,
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
