# Generated by Django 2.2.1 on 2019-12-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jeep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miledge", models.PositiveIntegerField()),
                ("task", models.CharField(max_length=128)),
                ("date", models.DateField()),
                ("mechanic", models.CharField(max_length=32)),
                ("parts_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("labor_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("details", models.TextField()),
            ],
        ),
    ]
