# Generated by Django 2.2.1 on 2019-12-29 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jeep", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jeep",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2019, 12, 29, 19, 15, 7, 204272)
            ),
        ),
        migrations.AlterField(
            model_name="jeep",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jeep",
            name="labor_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="jeep",
            name="mechanic",
            field=models.CharField(default="Miłosz", max_length=32),
        ),
        migrations.AlterField(
            model_name="jeep",
            name="parts_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
