# Generated by Django 2.2.1 on 2019-12-29 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jeep", "0002_auto_20191229_1915"),
    ]

    operations = [
        migrations.AddField(
            model_name="jeep", name="done", field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="jeep",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2019, 12, 29, 19, 19, 57, 480327)
            ),
        ),
    ]
