# Generated by Django 2.2.1 on 2019-12-29 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jeep", "0003_auto_20191229_1919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jeep",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2019, 12, 29, 19, 37, 51, 314097)
            ),
        ),
    ]
