# Generated by Django 2.2.1 on 2019-12-29 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeep', '0005_auto_20191229_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeep',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 29, 22, 24, 21, 506189)),
        ),
    ]
