# Generated by Django 2.2.1 on 2020-01-01 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jeep", "0008_auto_20200101_1955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jeep",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2020, 1, 1, 21, 3, 37, 790796)
            ),
        ),
    ]
