# Generated by Django 2.2.1 on 2019-12-29 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shooting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pistol", "Pistolet"),
                            ("rifle", "Karabin"),
                            ("gun", "Strzelba"),
                        ],
                        max_length=16,
                    ),
                ),
                ("year", models.PositiveIntegerField(default=2020)),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(2019, 12, 29, 19, 37, 51, 314940)
                    ),
                ),
                ("place", models.CharField(max_length=128)),
                ("competition", models.CharField(max_length=32)),
                ("score", models.CharField(blank=True, max_length=32, null=True)),
                ("confirmation", models.FileField(blank=True, null=True, upload_to="")),
                ("done", models.BooleanField(default=True)),
            ],
        ),
    ]
