# Generated by Django 2.2.1 on 2019-12-29 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shooting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shooting",
            name="confirmation",
            field=models.FileField(blank=True, null=True, upload_to="shooting/%Y"),
        ),
        migrations.AlterField(
            model_name="shooting",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2019, 12, 29, 19, 42, 32, 239726)
            ),
        ),
    ]
