# Generated by Django 2.2.1 on 2020-01-01 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shooting", "0004_auto_20200101_1954"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shooting",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2020, 1, 1, 19, 55, 54, 887641)
            ),
        ),
    ]
