# Generated by Django 2.2.1 on 2020-01-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Todo"),
                            ("in_progress", "In Progress"),
                            ("hold", "On Hold"),
                            ("done", "Done"),
                            ("plan", "Plan"),
                        ],
                        max_length=64,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("task", models.CharField(max_length=256)),
                ("comment", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
